"""Lazy public router for the complete headless session surface."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS = {
    "accepts_norm_aggregate": "xrd_tools.session.scan_norm",
    "acquire_light_1d_retention": "xrd_tools.session.light_1d_retention",
    "admit_run_configuration": "xrd_tools.session.run_configuration",
    "Capability": "xrd_tools.session.frame_projection",
    "CapabilityDisposition": "xrd_tools.session.frame_projection",
    "CapabilityState": "xrd_tools.session.frame_projection",
    "channel_is_partial": "xrd_tools.session.scan_norm",
    "display_capabilities": "xrd_tools.session.frame_projection",
    "DisplayCapabilities": "xrd_tools.session.frame_projection",
    "DynamicAccountingLimits": "xrd_tools.session.dynamic_accounting",
    "DynamicAttemptState": "xrd_tools.session.dynamic_accounting",
    "DynamicAttemptToken": "xrd_tools.session.dynamic_accounting",
    "DynamicCleanupReceipt": "xrd_tools.session.dynamic_accounting",
    "DynamicFrameIdentity": "xrd_tools.session.dynamic_accounting",
    "DynamicGroupHighWater": "xrd_tools.session.dynamic_accounting",
    "DynamicRunAccounting": "xrd_tools.session.dynamic_accounting",
    "DynamicRunSnapshot": "xrd_tools.session.dynamic_accounting",
    "DynamicRunState": "xrd_tools.session.dynamic_accounting",
    "dump_run_intent_profile": "xrd_tools.session.run_intent_profile",
    "empty_norm_aggregate": "xrd_tools.session.scan_norm",
    "FlushPolicy": "xrd_tools.session.policy",
    "fold_norm_metadata": "xrd_tools.session.scan_norm",
    "FrameEvent": "xrd_tools.session.scan_session",
    "FrameProjection": "xrd_tools.session.frame_projection",
    "FrameRecordStore": "xrd_tools.session.frame_record_store",
    "FrameHydrationRequest": "xrd_tools.session.frame_record_store",
    "FrameHydrationResult": "xrd_tools.session.frame_record_store",
    "FrozenGIConfiguration": "xrd_tools.session.run_configuration",
    "FrozenRunConfiguration": "xrd_tools.session.run_configuration",
    "FrozenSourceSpec": "xrd_tools.session.run_configuration",
    "FrozenThresholdPolicy": "xrd_tools.session.run_configuration",
    "get_pool": "xrd_tools.session.io_coordination",
    "GI_MOTOR_PREFERENCE": "xrd_tools.session.gi_motor",
    "GIIntent": "xrd_tools.session.run_configuration",
    "GUIThreadHydrationRefused": "xrd_tools.session.light_1d_retention",
    "H5FilePool": "xrd_tools.session.io_coordination",
    "HydrationCompletion": "xrd_tools.session.hydration",
    "HydrationOutcome": "xrd_tools.session.hydration",
    "HydrationPurpose": "xrd_tools.session.hydration",
    "HydrationReadKey": "xrd_tools.session.hydration",
    "HydrationScope": "xrd_tools.session.hydration",
    "HydrationToken": "xrd_tools.session.hydration",
    "IntentCommitAccepted": "xrd_tools.session.intent_store",
    "IntentFreezeAccepted": "xrd_tools.session.intent_store",
    "IntentRecaptureRequired": "xrd_tools.session.intent_store",
    "ItemDisposition": "xrd_tools.session.stage_accounting",
    "jsonable_run_value": "xrd_tools.session.run_configuration",
    "Light1DBorrow": "xrd_tools.session.light_1d_retention",
    "Light1DBufferLayout": "xrd_tools.session.light_1d_retention",
    "Light1DCleanupHooks": "xrd_tools.session.light_1d_retention",
    "Light1DCleanupPending": "xrd_tools.session.light_1d_retention",
    "Light1DCleanupReceipt": "xrd_tools.session.light_1d_retention",
    "Light1DCleanupToken": "xrd_tools.session.light_1d_retention",
    "Light1DCustodySlot": "xrd_tools.session.light_1d_retention",
    "Light1DCustodyState": "xrd_tools.session.light_1d_retention",
    "Light1DFundingMode": "xrd_tools.session.light_1d_retention",
    "Light1DHydrationToken": "xrd_tools.session.light_1d_retention",
    "Light1DLayout": "xrd_tools.session.light_1d_retention",
    "Light1DLeaseState": "xrd_tools.session.light_1d_retention",
    "Light1DModeData": "xrd_tools.session.light_1d_retention",
    "Light1DModeLayout": "xrd_tools.session.light_1d_retention",
    "Light1DRecord": "xrd_tools.session.light_1d_retention",
    "Light1DReleaseReceipt": "xrd_tools.session.light_1d_retention",
    "Light1DRetainedCustodyReceipt": "xrd_tools.session.light_1d_retention",
    "Light1DRetentionLease": "xrd_tools.session.light_1d_retention",
    "Light1DStaleGeneration": "xrd_tools.session.light_1d_retention",
    "Light1DUnavailable": "xrd_tools.session.light_1d_retention",
    "load_run_intent_profile": "xrd_tools.session.run_intent_profile",
    "metadata_row_from_provider": "xrd_tools.session.frame_projection",
    "metadata_row_from_record": "xrd_tools.session.frame_projection",
    "metadata_row_from_view": "xrd_tools.session.frame_projection",
    "MetadataConflictError": "xrd_tools.session.frame_projection",
    "MetadataRow": "xrd_tools.session.frame_projection",
    "next_norm_revision": "xrd_tools.session.scan_norm",
    "normalization_channels": "xrd_tools.session.frame_projection",
    "normalization_value": "xrd_tools.session.frame_projection",
    "pick_default_gi_motor": "xrd_tools.session.gi_motor",
    "ProgressEvent": "xrd_tools.session.scan_session",
    "PROFILE_SCHEMA": "xrd_tools.session.run_intent_profile",
    "PROFILE_VERSION": "xrd_tools.session.run_intent_profile",
    "project_frame": "xrd_tools.session.frame_projection",
    "require_run_configuration": "xrd_tools.session.run_configuration",
    "required_result_modes": "xrd_tools.session.scan_session",
    "resolve_gi_motor": "xrd_tools.session.run_configuration",
    "resolve_session_policy": "xrd_tools.session.policy",
    "ResultMode": "xrd_tools.session.stage_accounting",
    "RunConfigurationRefused": "xrd_tools.session.run_configuration",
    "RunIntent": "xrd_tools.session.run_configuration",
    "RunIntentProfileError": "xrd_tools.session.run_intent_profile",
    "RunIntentSnapshot": "xrd_tools.session.intent_store",
    "RunIntentStore": "xrd_tools.session.intent_store",
    "ScanNormAggregate": "xrd_tools.session.scan_norm",
    "ScanSession": "xrd_tools.session.scan_session",
    "SessionEnvelopeError": "xrd_tools.session.policy",
    "SessionPolicy": "xrd_tools.session.policy",
    "SessionResourceAllocation": "xrd_tools.session.policy",
    "SessionResourceAuthority": "xrd_tools.session.light_1d_retention",
    "SessionResourceAuthoritySnapshot": "xrd_tools.session.light_1d_retention",
    "SessionResourceRequirements": "xrd_tools.session.policy",
    "StageLedger": "xrd_tools.session.stage_accounting",
    "StageReceipt": "xrd_tools.session.stage_accounting",
    "StageSnapshot": "xrd_tools.session.stage_accounting",
    "StateChangeEvent": "xrd_tools.session.scan_session",
    "ThresholdIntent": "xrd_tools.session.run_configuration",
    "wavelength_evidence": "xrd_tools.session.frame_projection",
    "WavelengthEvidence": "xrd_tools.session.frame_projection",
    "WavelengthStatus": "xrd_tools.session.frame_projection",
}

__all__ = sorted(_EXPORTS)

def __getattr__(name: str) -> Any:
    try:
        module_name = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
