"""Lazy public IO export router.

Preview/source APIs and the H23 transaction, writer, and Append surfaces are
loaded only when requested so lightweight IO imports remain dependency-pure.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS = {
    "aggregate_1d": ("xrd_tools.io.aggregate", "aggregate_1d"),
    "aggregate_2d": ("xrd_tools.io.aggregate", "aggregate_2d"),
    "Aggregated1D": ("xrd_tools.io.aggregate", "Aggregated1D"),
    "Aggregated2D": ("xrd_tools.io.aggregate", "Aggregated2D"),
    "AppendCommittedPrefix": ("xrd_tools.io.append", "AppendCommittedPrefix"),
    "AppendDecision": ("xrd_tools.io.append", "AppendDecision"),
    "AppendDisposition": ("xrd_tools.io.append", "AppendDisposition"),
    "AppendExternalMember": ("xrd_tools.io.append", "AppendExternalMember"),
    "AppendImageMember": ("xrd_tools.io.append", "AppendImageMember"),
    "AppendIntent": ("xrd_tools.io.append", "AppendIntent"),
    "AppendPreflight": ("xrd_tools.io.append", "AppendPreflight"),
    "AppendPreflightCleanupError": ("xrd_tools.io.append", "AppendPreflightCleanupError"),
    "AppendPreflightSnapshot": ("xrd_tools.io.append", "AppendPreflightSnapshot"),
    "AppendPreflightState": ("xrd_tools.io.append", "AppendPreflightState"),
    "AppendRefused": ("xrd_tools.io.append", "AppendRefused"),
    "AppendSource": ("xrd_tools.io.append", "AppendSource"),
    "AppendSourceGraphRefused": ("xrd_tools.io.append", "AppendSourceGraphRefused"),
    "apply_rotation": ("xrd_tools.io.image", "apply_rotation"),
    "begin_same_run_lineage": ("xrd_tools.io.append", "begin_same_run_lineage"),
    "classify_image_source": ("xrd_tools.io.image_source", "classify_image_source"),
    "CleanupIncomplete": ("xrd_tools.io.output_transaction", "CleanupIncomplete"),
    "CleanupToken": ("xrd_tools.io.output_transaction", "CleanupToken"),
    "commit_append_lineage": ("xrd_tools.io.append", "commit_append_lineage"),
    "decode_committed_append_prefix": ("xrd_tools.io.append", "decode_committed_append_prefix"),
    "COMMON_RAW_DETECTOR_SHAPES": ("xrd_tools.io.image", "COMMON_RAW_DETECTOR_SHAPES"),
    "connect_tiled": ("xrd_tools.io.tiled", "connect_tiled"),
    "count_frames": ("xrd_tools.io.image", "count_frames"),
    "adaptive_chunk_size": ("xrd_tools.io.chunk_size", "adaptive_chunk_size"),
    "default_output_path": ("xrd_tools.io.output_path", "default_output_path"),
    "DetectorPreviewProjection": ("xrd_tools.io.frame_preview", "DetectorPreviewProjection"),
    "extend_same_run_lineage": ("xrd_tools.io.append", "extend_same_run_lineage"),
    "find_image_files": ("xrd_tools.io.image", "find_image_files"),
    "find_nexus_image_dataset": ("xrd_tools.io.nexus", "find_nexus_image_dataset"),
    "frame_record_write_parts": ("xrd_tools.io.nexus", "frame_record_write_parts"),
    "FramePreview": ("xrd_tools.io.frame_preview", "FramePreview"),
    "FrameViewReader": ("xrd_tools.io.frame_view", "FrameViewReader"),
    "get_angles": ("xrd_tools.io.spec", "get_angles"),
    "get_1d": ("xrd_tools.io.read", "get_1d"),
    "get_2d": ("xrd_tools.io.read", "get_2d"),
    "get_average_finite_counts": (
        "xrd_tools.io.read", "get_average_finite_counts",
    ),
    "get_detector_mask": ("xrd_tools.io.image", "get_detector_mask"),
    "get_energy_and_UB": ("xrd_tools.io.spec", "get_energy_and_UB"),
    "get_from_spec_file": ("xrd_tools.io.spec", "get_from_spec_file"),
    "get_frames": ("xrd_tools.io.read", "get_frames"),
    "get_metadata": ("xrd_tools.io.read", "get_metadata"),
    "get_output_transaction_coordinator": ("xrd_tools.io.output_transaction", "get_output_transaction_coordinator"),
    "get_scan_path_info": ("xrd_tools.io.spec", "get_scan_path_info"),
    "get_raw_frame": ("xrd_tools.io.read", "get_raw_frame"),
    "get_spec_scan_type": ("xrd_tools.io.spec", "get_spec_scan_type"),
    "get_spec_scanned_axes": ("xrd_tools.io.spec", "get_spec_scanned_axes"),
    "get_thumbnail": ("xrd_tools.io.read", "get_thumbnail"),
    "ImageSourceInfo": ("xrd_tools.io.image_source", "ImageSourceInfo"),
    "ImageSourceKind": ("xrd_tools.io.image_source", "ImageSourceKind"),
    "infer_raw_detector_shape": ("xrd_tools.io.image", "infer_raw_detector_shape"),
    "inspect_nexus": ("xrd_tools.io.nexus_inspect", "inspect_nexus"),
    "Integrated1D": ("xrd_tools.io.read", "Integrated1D"),
    "Integrated2D": ("xrd_tools.io.read", "Integrated2D"),
    "is_readable_output_path": ("xrd_tools.io.output_path", "is_readable_output_path"),
    "iter_frame_records": ("xrd_tools.io.frame_view", "iter_frame_records"),
    "iter_frame_views": ("xrd_tools.io.frame_view", "iter_frame_views"),
    "LeaseOwner": ("xrd_tools.io.output_transaction", "LeaseOwner"),
    "LeaseSnapshot": ("xrd_tools.io.output_transaction", "LeaseSnapshot"),
    "LeaseUnavailable": ("xrd_tools.io.output_transaction", "LeaseUnavailable"),
    "LEGACY_OUTPUT_SUFFIX": ("xrd_tools.io.output_path", "LEGACY_OUTPUT_SUFFIX"),
    "list_entries": ("xrd_tools.io.nexus", "list_entries"),
    "list_scans": ("xrd_tools.io.tiled", "list_scans"),
    "load_image_frame": ("xrd_tools.io.image_source", "load_image_frame"),
    "load_mask": ("xrd_tools.io.image", "load_mask"),
    "load_processed_raw_or_thumbnail": ("xrd_tools.io.image_source", "load_processed_raw_or_thumbnail"),
    "NEW_OUTPUT_SUFFIX": ("xrd_tools.io.output_path", "NEW_OUTPUT_SUFFIX"),
    "nexus_info": ("xrd_tools.io.image", "nexus_info"),
    "NexusAxisSummary": ("xrd_tools.io.nexus_inspect", "NexusAxisSummary"),
    "NexusDatasetData": ("xrd_tools.io.nexus_inspect", "NexusDatasetData"),
    "NexusDatasetPreview": ("xrd_tools.io.nexus_inspect", "NexusDatasetPreview"),
    "NexusFileSummary": ("xrd_tools.io.nexus_inspect", "NexusFileSummary"),
    "NexusNodeSummary": ("xrd_tools.io.nexus_inspect", "NexusNodeSummary"),
    "NexusRecordWriter": ("xrd_tools.io.record_writer", "NexusRecordWriter"),
    "NexusReducedSummary": ("xrd_tools.io.nexus_inspect", "NexusReducedSummary"),
    "NexusXDartSummary": ("xrd_tools.io.nexus_inspect", "NexusXDartSummary"),
    "observe_resolved_raw_source": ("xrd_tools.io.read", "observe_resolved_raw_source"),
    "open_nexus_writer": ("xrd_tools.io.nexus", "open_nexus_writer"),
    "open_scan": ("xrd_tools.io.read", "open_scan"),
    "OutputTransaction": ("xrd_tools.io.output_transaction", "OutputTransaction"),
    "OutputTransactionCoordinator": ("xrd_tools.io.output_transaction", "OutputTransactionCoordinator"),
    "OutputTransactionError": ("xrd_tools.io.output_transaction", "OutputTransactionError"),
    "OutputReceiptCapability": ("xrd_tools.io.output_transaction", "OutputReceiptCapability"),
    "OutputReceiptCapabilityProvider": ("xrd_tools.io.output_transaction", "OutputReceiptCapabilityProvider"),
    "OwnershipRefused": ("xrd_tools.io.output_transaction", "OwnershipRefused"),
    "OwnerToken": ("xrd_tools.io.output_transaction", "OwnerToken"),
    "prepare_append_preflight": ("xrd_tools.io.append", "prepare_append_preflight"),
    "preview_nexus_dataset": ("xrd_tools.io.nexus_inspect", "preview_nexus_dataset"),
    "PROCESSED_SCHEMA_VERSION": ("xrd_tools.io.schema", "PROCESSED_SCHEMA_VERSION"),
    "ProcessedScan": ("xrd_tools.io.read", "ProcessedScan"),
    "qualify_append": ("xrd_tools.io.append", "qualify_append"),
    "RawFrameResult": ("xrd_tools.io.image_source", "RawFrameResult"),
    "RawSourceObservation": ("xrd_tools.io.read", "RawSourceObservation"),
    "read_frame_record": ("xrd_tools.io.frame_view", "read_frame_record"),
    "read_frame_records": ("xrd_tools.io.frame_view", "read_frame_records"),
    "read_frame_preview": ("xrd_tools.io.frame_preview", "read_frame_preview"),
    "read_frame_view": ("xrd_tools.io.frame_view", "read_frame_view"),
    "read_frame_views": ("xrd_tools.io.frame_view", "read_frame_views"),
    "read_image": ("xrd_tools.io.image", "read_image"),
    "read_image_metadata": ("xrd_tools.io.metadata", "read_image_metadata"),
    "read_image_stack": ("xrd_tools.io.image", "read_image_stack"),
    "read_images_parallel": ("xrd_tools.io.image", "read_images_parallel"),
    "read_nexus": ("xrd_tools.io.nexus", "read_nexus"),
    "read_nexus_dataset": ("xrd_tools.io.nexus_inspect", "read_nexus_dataset"),
    "read_nexus_frame": ("xrd_tools.io.image", "read_nexus_frame"),
    "read_pdi_metadata": ("xrd_tools.io.metadata", "read_pdi_metadata"),
    "read_scan": ("xrd_tools.io.nexus", "read_scan"),
    "read_scan_data": ("xrd_tools.io.read", "read_scan_data"),
    "read_scan_metadata": ("xrd_tools.io.nexus", "read_scan_metadata"),
    "read_stitched": ("xrd_tools.io.nexus", "read_stitched"),
    "read_tiled_run": ("xrd_tools.io.tiled", "read_tiled_run"),
    "read_txt_metadata": ("xrd_tools.io.metadata", "read_txt_metadata"),
    "read_xye": ("xrd_tools.io.export", "read_xye"),
    "READABLE_OUTPUT_SUFFIXES": ("xrd_tools.io.output_path", "READABLE_OUTPUT_SUFFIXES"),
    "RecordWrite": ("xrd_tools.io.record_writer", "RecordWrite"),
    "relative_source_path": ("xrd_tools.io.read", "relative_source_path"),
    "resolve_detector_shape": ("xrd_tools.io.image", "resolve_detector_shape"),
    "resolve_output_target": ("xrd_tools.io.output_path", "resolve_output_target"),
    "resolve_source_master": ("xrd_tools.io.read", "resolve_source_master"),
    "resolved_raw_source": ("xrd_tools.io.read", "resolved_raw_source"),
    "RetryAction": ("xrd_tools.io.output_transaction", "RetryAction"),
    "Scan": ("xrd_tools.io.read", "Scan"),
    "SCHEMA": ("xrd_tools.io.schema", "SCHEMA"),
    "science_fingerprint": ("xrd_tools.io.append", "science_fingerprint"),
    "stage_append_lineage": ("xrd_tools.io.append", "stage_append_lineage"),
    "StreamAttempt": ("xrd_tools.io.output_transaction", "StreamAttempt"),
    "StreamCheckpoint": ("xrd_tools.io.output_transaction", "StreamCheckpoint"),
    "StreamTerminal": ("xrd_tools.io.output_transaction", "StreamTerminal"),
    "SUPPORTED_EXTS": ("xrd_tools.io.image", "SUPPORTED_EXTS"),
    "TargetAdmission": ("xrd_tools.io.output_transaction", "TargetAdmission"),
    "TargetChanged": ("xrd_tools.io.output_transaction", "TargetChanged"),
    "TargetLease": ("xrd_tools.io.output_transaction", "TargetLease"),
    "TargetSnapshot": ("xrd_tools.io.output_transaction", "TargetSnapshot"),
    "TransactionPhase": ("xrd_tools.io.output_transaction", "TransactionPhase"),
    "TransactionSnapshot": ("xrd_tools.io.output_transaction", "TransactionSnapshot"),
    "TransactionStateError": ("xrd_tools.io.output_transaction", "TransactionStateError"),
    "truncate_append_epoch": ("xrd_tools.io.append", "truncate_append_epoch"),
    "truncate_append_source": ("xrd_tools.io.append", "truncate_append_source"),
    "upsert_per_frame_geometry": ("xrd_tools.io.nexus", "upsert_per_frame_geometry"),
    "upsert_positioners": ("xrd_tools.io.nexus", "upsert_positioners"),
    "upsert_scan_metadata": ("xrd_tools.io.nexus", "upsert_scan_metadata"),
    "validate_integrated_stack_write": ("xrd_tools.io.nexus", "validate_integrated_stack_write"),
    "write_frame_records": ("xrd_tools.io.nexus", "write_frame_records"),
    "write_h5": ("xrd_tools.io.export", "write_h5"),
    "write_integrated_stack": ("xrd_tools.io.nexus", "write_integrated_stack"),
    "write_nexus": ("xrd_tools.io.nexus", "write_nexus"),
    "write_nexus_frame": ("xrd_tools.io.nexus", "write_nexus_frame"),
    "write_per_frame_geometry": ("xrd_tools.io.nexus", "write_per_frame_geometry"),
    "write_positioners": ("xrd_tools.io.nexus", "write_positioners"),
    "write_scan_metadata": ("xrd_tools.io.nexus", "write_scan_metadata"),
    "write_stitched": ("xrd_tools.io.nexus", "write_stitched"),
    "write_xye": ("xrd_tools.io.export", "write_xye"),
    "WriterFinalization": ("xrd_tools.io.record_writer", "WriterFinalization"),
    "WriterIncomplete": ("xrd_tools.io.record_writer", "WriterIncomplete"),
    "WriterOperationVector": ("xrd_tools.io.record_writer", "WriterOperationVector"),
    "WriterOutcome": ("xrd_tools.io.record_writer", "WriterOutcome"),
    "WriterPhase": ("xrd_tools.io.record_writer", "WriterPhase"),
    "WriterStateError": ("xrd_tools.io.record_writer", "WriterStateError"),
    "WriterTransactionBinding": ("xrd_tools.io.record_writer", "WriterTransactionBinding"),
    "XyeOutputTransaction": ("xrd_tools.io.output_transaction", "XyeOutputTransaction"),
    "XyeSnapshot": ("xrd_tools.io.output_transaction", "XyeSnapshot"),
}

__all__ = sorted(_EXPORTS)

def __getattr__(name: str) -> Any:
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
    value = getattr(import_module(module_name), attribute)
    globals()[name] = value
    return value
