"""Qt-free lifecycle kernel for the scattering workspace vNext experiment."""

from .contracts import (
    RunExecutorPort,
    SourceCapture,
    SourcePort,
    SourceSelection,
)
from .coordinator import ScatteringCoordinator
from .events import (
    CleanupStatus,
    DurablePaused,
    DurableFinal,
    ExecutorAccepted,
    ExecutorStartFailed,
    ExecutionEnded,
    FatalExecution,
    LifecycleError,
    LifecycleResult,
    LifecycleStatus,
    OwnersClosed,
    PauseRequested,
    PreflightAccepted,
    PreflightRefused,
    RequestId,
    ResumeRequested,
    Resumed,
    RunIdentity,
    StopRequested,
)
from .state_machine import IllegalTransition, RunPhase, RunSignal, transition
from .start_outcomes import (
    ExceptionDetail,
    RecoveryFailure,
    StartCapture,
    StartClosed,
    StartFailed,
    StartFailureKind,
    StartLaunched,
    StartRecaptureCause,
    StartRecaptureRequired,
    StartRefusal,
    StartRefused,
    StartRejected,
    StartRejection,
)
from .start_pipeline import StartPipeline
from .context_controller import ContextController
from .context_projection import ContextProjection, ProjectionRequest
from .browse_values import (
    BrowseLoadOutcome,
    BrowseLoadRequest,
    BrowseLoadStatus,
)

__all__ = [
    "CleanupStatus",
    "BrowseLoadOutcome",
    "BrowseLoadRequest",
    "BrowseLoadStatus",
    "ContextController",
    "ContextProjection",
    "DurablePaused",
    "DurableFinal",
    "ExecutorAccepted",
    "ExecutorStartFailed",
    "ExecutionEnded",
    "ExceptionDetail",
    "FatalExecution",
    "IllegalTransition",
    "LifecycleError",
    "LifecycleResult",
    "LifecycleStatus",
    "OwnersClosed",
    "PauseRequested",
    "PreflightAccepted",
    "PreflightRefused",
    "RequestId",
    "ResumeRequested",
    "Resumed",
    "RecoveryFailure",
    "RunExecutorPort",
    "RunIdentity",
    "RunPhase",
    "RunSignal",
    "SourceCapture",
    "SourcePort",
    "SourceSelection",
    "ScatteringCoordinator",
    "StartCapture",
    "StartClosed",
    "StartFailed",
    "StartFailureKind",
    "StartLaunched",
    "StartPipeline",
    "StartRecaptureCause",
    "StartRecaptureRequired",
    "StartRefusal",
    "StartRefused",
    "StartRejected",
    "StartRejection",
    "StopRequested",
    "ProjectionRequest",
    "transition",
]
